spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.31.20.148:3306/juhai?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 118.31.20.148
    port: 6378
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

security:
  jwt:
    key-store: classpath:auth-jwt.jks
    key-store-password: followme
    key-pair-alias: auth-jwt
    key-pair-password: followme

logging:
  level:
    com.zan.hu.auth: debug
server:
  port: 8201
