spring:
  redis:
    host: 118.31.20.148
    port: 6378
  jackson:
    default-property-inclusion: non_null
  #mysql db
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.31.20.148:3306/zan?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

security:
  jwt:
    key-store: classpath:auth-jwt.jks
    key-store-password: followme
    key-pair-alias: auth-jwt
    key-pair-password: followme

logging:
  level:
    com.zan.hu.auth: info
server:
  port: 8201

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  request:
    interceptor:
      enable: false
redis:
  basic:
    server:
      enable: true

